#ifndef VisualEngine_VEcommon_h
#define VisualEngine_VEcommon_h

enum VE_BUFFER_MODE
{
    VE_BUFFER_MODE_POSITION,
    VE_BUFFER_MODE_POSITION_TEXTURE,
    VE_BUFFER_MODE_POSITION_NORMAL,
    VE_BUFFER_MODE_ALL
};

enum VE_RENDER_MODE
{
    VE_RENDER_MODE_DEPTH,
    VE_RENDER_MODE_LIGHT,
    VE_RENDER_MODE_TEXTURE,
    VE_RENDER_MODE_SELECTION
};

enum VE_TRANSITION_EFFECT
{
    VE_TRANSITION_EFFECT_NONE,
    VE_TRANSITION_EFFECT_HARD,
    VE_TRANSITION_EFFECT_EASE,
    VE_TRANSITION_EFFECT_END_EASE,
    VE_TRANSITION_EFFECT_BEGIN_EASE,
    VE_TRANSITION_EFFECT_END_SUPER_SMOOTH
};

enum VE_VIEW_TYPE
{
    VE_VIEW_TYPE_DIRECT,
    VE_VIEW_TYPE_TEXTURE
};

enum VE_CAMERA_TYPE
{
    VE_CAMERA_TYPE_PERSPECTIVE,
    VE_CAMERA_TYPE_ORTHOGRAPHIC
};

enum VE_FBO_TYPE
{
    VE_FBO_TYPE_COLOR,
    VE_FBO_TYPE_COLOR_DEPTH_TEST,
    VE_FBO_TYPE_DEPTH,
    VE_FBO_TYPE_BOTH
};

enum VE_WATCH_STRING_FORMAT
{
	VE_WATCH_STRING_FORMAT_CENTSECONDS,
	VE_WATCH_STRING_FORMAT_SECONDS,
	VE_WATCH_STRING_FORMAT_MINUTES,
	VE_WATCH_STRING_FORMAT_HOURS,
	VE_WATCH_STRING_FORMAT_SECONDS_CENTSECONDS,
	VE_WATCH_STRING_FORMAT_MINUTES_SECONDS,
	VE_WATCH_STRING_FORMAT_MINUTES_SECONDS_CENTSECONDS,
	VE_WATCH_STRING_FORMAT_HOURS_MINUTES,
	VE_WATCH_STRING_FORMAT_HOURS_MINUTES_SECONDS,
	VE_WATCH_STRING_FORMAT_HOURS_MINUTES_SECONDS_CENTSECONDS
};

enum VE_WATCH_STYLE
{
	VE_WATCH_STYLE_FREE,
	VE_WATCH_STYLE_REVERSE,
	VE_WATCH_STYLE_LIMITED
};

enum VE_PIVOT_ROTATION
{
	VE_PIVOT_ROTATION_XYZ,
	VE_PIVOT_ROTATION_XZY,
	VE_PIVOT_ROTATION_YXZ,
	VE_PIVOT_ROTATION_YZX,
	VE_PIVOT_ROTATION_ZXY,
	VE_PIVOT_ROTATION_ZYX
};

#endif
